spring:
  myname: llj
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.1.214:3306/demo?useSSL=true
    username: hive
    password: hivehive
    druid:
      #dirver-class-name: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      max-active: 50
      min-idle: 10
      max-wait: 6000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      #min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis: 1000000
      #pool-prepared-statements: true #for oracle
      #max-pool-prepared-statement-per-connection-size: 0 #for oracle
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      #aop-patterns:
      stat-view-servlet:
        enabled: true
        #url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        #allow: 172.168.3.91
        #deny: 172.168.2.90
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '/static/*,/druid/*,/favicon.ico'
        profile-enable: true

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  
  redis:
    host: 10.1.1.222
    port: 6379
    password:
    database: 14
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 100  
  kafka:
    bootstrap-servers: 10.1.1.240:9092,10.1.1.241:9092,10.1.1.242:9092
    consumer:
      group-id: springbootGroup
      enable-auto-commit: true
      #key-deserializer:
      #value-deserializer:
    producer:
      #key-serializer:
      #value-serializer:
      acks: 1

  
